name: Build and Deploy to Kubernetes (Local)

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # <-- important change

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sumeetp111/portfolio:latest
          cache-from: type=registry,ref=sumeetp111/portfolio:cache
          cache-to: type=registry,ref=sumeetp111/portfolio:cache,mode=max

      - name: Restart Kubernetes deployment
        run: |
          kubectl rollout restart deployment portfolio-deployment

